/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#142175',
        'primary-dark': '#0d1757',
        'primary-container': '#2e3a8c',
        'primary-fixed': '#dfe0ff',
        'primary-fixed-dim': '#bcc3ff',
        'on-primary': '#ffffff',
        'on-primary-container': '#9ea9ff',
        secondary: '#505f76',
        'secondary-container': '#d0e1fb',
        'secondary-fixed': '#d3e4fe',
        'on-secondary': '#ffffff',
        'on-secondary-fixed': '#0b1c30',
        'on-secondary-fixed-variant': '#38485d',
        surface: '#fbf8ff',
        'surface-dim': '#dbd9e1',
        'surface-bright': '#fbf8ff',
        'surface-container': '#efedf4',
        'surface-container-low': '#f5f2fa',
        'surface-container-high': '#e9e7ef',
        'surface-container-highest': '#e4e1e9',
        'surface-container-lowest': '#ffffff',
        'surface-variant': '#e4e1e9',
        'on-surface': '#1b1b21',
        'on-surface-variant': '#454651',
        background: '#fbf8ff',
        'on-background': '#1b1b21',
        outline: '#767682',
        'outline-variant': '#c6c5d3',
        'tertiary-fixed': '#ffdbc7',
        'tertiary-fixed-dim': '#ffb689',
        tertiary: '#4b2000',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed-variant': '#723603',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
